//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Account_Type { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<sbyte> Gender { get; set; }
        public Nullable<int> Gender_Pref { get; set; }
        public Nullable<int> Credit_Amount { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public string Profile_Pic { get; set; }
        public string Gallery_Pics { get; set; }
        public string Private_Gallery_Pics { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public Nullable<short> Online_Status { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> Score { get; set; }
        public string Ethnicity { get; set; }
        public string Interests { get; set; }
    }
}
